version: '3.9'

services:
  pocker.infra.database:
    container_name: pocker.infra.database
    image: postgres:16.1-alpine3.19
    restart: always
    environment:
      - POSTGRES_USER=${POCKER__DB_USER}
      - POSTGRES_PASSWORD=${POCKER__DB_PASSWORD}
      - POSTGRES_DB=${POCKER__DB_NAME}
    ports:
      - ${POCKER__DB_PORT}:5432
    volumes:
      - pocker.volumes.db:/var/lib/postgresql/data
    networks:
      - pocker.network

  pocker.infra.database.console:
    container_name: pocker.infra.database.console
    image: dpage/pgadmin4:8.2
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POCKER__DB_CONSOLE_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POCKER__DB_CONSOLE_PASSWORD}
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - ${POCKER__DB_CONSOLE_PORT}:80
    volumes:
      - pocker.volumes.db_console:/var/lib/pgadmin
    networks:
      - pocker.network

volumes:
  pocker.volumes.db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mounted/db'
  
  pocker.volumes.db_console:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './mounted/db_console'

networks:
  pocker.network:
    driver: bridge